version: 2
jobs:
  build:
    docker:
      - image: semperfi93/circleci-rancher-node:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - run:
          name: "Build & Push Docker Image"
          command: |
            docker build -t $REPOSITORY_NAME -f ./Dockerfile-dev .
            docker tag $REPOSITORY_NAME:latest $REPOISTORY_URL/$REPOSITORY_NAME:latest
            docker push $REPOISTORY_URL/$REPOSITORY_NAME:latest
      - run:
          name: "Deploy to rancher"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              rancher export $RANCHER_STACK_NAME && \
              rm -rf rancher-$RANCHER_STACK_NAME && \
              mv $RANCHER_STACK_NAME rancher-$RANCHER_STACK_NAME && \
              cd rancher-$RANCHER_STACK_NAME && \
              rancher-compose -p $RANCHER_STACK_NAME up --pull --force-upgrade --confirm-upgrade -d
            fi
