# INSTALL UBUNTU
FROM node:8.11.3

# Making docker run npm install only if changes are made to package.json
ADD package.json /tmp/package.json
RUN cd /tmp && npm install

# /<working directory name>
RUN mkdir -p /koajs-demo && cp -a /tmp/node_modules /koajs_demo

#Add local repo to docker instance
ADD . /koajs_demo
WORKDIR /koajs_demo
# RUN cp .env .env
# RUN WEB_URL=$(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}') && sed -i "s/localhost/$WEB_URL/g" .env

# Expose port
EXPOSE 4001

# Run app
CMD ["npm", "run", "start:dev"]