# INSTALL UBUNTU
FROM node:8.11.3

#INSTALL LIBAIO1 & UNZIP (NEEDED FOR STRONG-ORACLE)
RUN apt-get update \
  && apt-get install -y libaio1 \
  && apt-get install -y build-essential \
  && apt-get install -y unzip \
  && apt-get install -y curl \
  && apt-get install net-tools

#ADD ORACLE INSTANT CLIENT
RUN mkdir -p opt/oracle
RUN chmod -R 777 opt/oracle
COPY oracle/linux/ .

RUN unzip instantclient-basic-linux-x86-64-11.2.0.2.0.zip -d /opt/oracle \
  && unzip instantclient-sdk-linux-x86-64-11.2.0.2.0.zip -d /opt/oracle  \
  && mv /opt/oracle/instantclient_11_2 /opt/oracle/instantclient \
  && ln -s /opt/oracle/instantclient/libclntsh.so.11.1 /opt/oracle/instantclient/libclntsh.so \
  && ln -s /opt/oracle/instantclient/libocci.so.11.1 /opt/oracle/instantclient/libocci.so

ENV LD_LIBRARY_PATH="/opt/oracle/instantclient"
ENV OCI_HOME="/opt/oracle/instantclient"
ENV OCI_LIB_DIR="/opt/oracle/instantclient"
ENV OCI_INCLUDE_DIR="/opt/oracle/instantclient/sdk/include"

RUN echo '/opt/oracle/instantclient/' | tee -a /etc/ld.so.conf.d/oracle_instant_client.conf && ldconfig

# Making docker run npm install only if changes are made to package.json
ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /eplus-notification-api && cp -a /tmp/node_modules /eplus-notification-api

#Add local repo to docker instance
ADD . /eplus-notification-api
WORKDIR /eplus-notification-api
# RUN cp .env.example .env
# RUN WEB_URL=$(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}') && sed -i "s/localhost/$WEB_URL/g" .env

# Expose port
EXPOSE 4070

# Run app
CMD ["npm", "run", "start:dev"]